apiVersion: 1

datasources:
  - name: FacePulse DB
    type: postgres
    uid: facepulse-pg
    url: postgres:5432
    database: facepulse
    user: facepulse
    secureJsonData:
      password: facepulse
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
